package cli

import (
	"encoding/json"
	"os"
	"testing"
)

// TestEvidenceGoldenFixtureValidates loads the cross-language golden
// evidence fixture (generated by Go, validated by both Go and the
// TypeScript coordinator) and verifies the digest is correct. This is
// the Go side of the interoperability contract test.
func TestEvidenceGoldenFixtureValidates(t *testing.T) {
	data, err := os.ReadFile("testdata/evidence-golden.json")
	if err != nil {
		t.Fatal(err)
	}
	var wrapper struct {
		Evidence RunEvidenceV1 `json:"evidence"`
	}
	if err := json.Unmarshal(data, &wrapper); err != nil {
		t.Fatal(err)
	}
	ev := wrapper.Evidence
	if ev.Digest == "" {
		t.Fatal("golden evidence has empty digest")
	}
	if !VerifyRunEvidenceDigest(ev) {
		t.Fatalf("golden evidence digest %q does not match recomputed digest", ev.Digest)
	}
	if ev.SchemaVersion != 1 {
		t.Fatalf("golden evidence schema_version=%d, want 1", ev.SchemaVersion)
	}
	if ev.EvidenceType != "run" {
		t.Fatalf("golden evidence evidence_type=%q, want 'run'", ev.EvidenceType)
	}
}

// TestEvidenceGoldenFixtureDigestIsRawHex ensures the golden digest is a
// raw 64-character hex string (no sha256: prefix), matching the wire
// contract shared between Go and TypeScript.
func TestEvidenceGoldenFixtureDigestIsRawHex(t *testing.T) {
	data, err := os.ReadFile("testdata/evidence-golden.json")
	if err != nil {
		t.Fatal(err)
	}
	var wrapper struct {
		Evidence RunEvidenceV1 `json:"evidence"`
	}
	if err := json.Unmarshal(data, &wrapper); err != nil {
		t.Fatal(err)
	}
	d := wrapper.Evidence.Digest
	if len(d) != 64 {
		t.Fatalf("golden digest length=%d, want 64", len(d))
	}
	for _, c := range d {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
			t.Fatalf("golden digest %q contains non-hex character %q", d, string(c))
		}
	}
}
