package cli

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// TestGenerateTerminalBundleGolden creates a deterministic terminal bundle
// (evidence + signed V3 receipt) using a fixed Ed25519 seed and writes it
// to testdata/terminal-bundle-golden.json. The TypeScript test
// (worker/test/terminal-bundle-interop.test.ts) reads this file and
// verifies the receipt signature and evidence binding using the worker's
// own verification code.
//
// This is the cross-runtime receipt verification gate: it proves that a
// receipt signed by Go's Ed25519 implementation is verifiable by the
// TypeScript WebCrypto implementation, and that the evidence_sha256
// binding is consistent across both runtimes.
//
// Run with -update to regenerate the golden file.
func TestGenerateTerminalBundleGolden(t *testing.T) {
	// Use a fixed seed for deterministic key generation.
	seed := make([]byte, ed25519.SeedSize)
	for i := range seed {
		seed[i] = byte(i + 1)
	}
	key := ed25519.NewKeyFromSeed(seed)
	pub := key.Public().(ed25519.PublicKey)

	startedAt := time.Date(2026, 1, 15, 12, 30, 0, 0, time.UTC)
	endedAt := startedAt.Add(5 * time.Second)

	outcome := FinalRunOutcome{
		Provider:    "deterministic-test",
		LeaseID:     "cbx_golden001",
		Slug:        "golden-test",
		RunID:       "run_golden001",
		Command:     []string{"npm", "test"},
		CommandText: "npm test",
		ExitCode:    0,
		RunStatus:   RunStatusSucceeded,
		StartedAt:   startedAt,
		EndedAt:     endedAt,
		Timing: TimingReport{
			TotalMs:   5000,
			CommandMs: 3000,
			SyncMs:    2000,
		},
		TerminalLog: runLogSnapshot{
			Log: "all tests passed\n",
		},
	}

	bundle, err := BuildTerminalBundle(outcome, key)
	if err != nil {
		t.Fatalf("BuildTerminalBundle: %v", err)
	}

	// Verify the bundle is self-consistent.
	if err := verifyTerminalRunReceiptSignature(bundle.Receipt); err != nil {
		t.Fatalf("verify signature: %v", err)
	}
	if bundle.Receipt.EvidenceSHA256 != bundle.Evidence.Digest {
		t.Fatalf("evidence binding mismatch: receipt %s != evidence %s",
			bundle.Receipt.EvidenceSHA256, bundle.Evidence.Digest)
	}

	// Serialize the golden file.
	golden := map[string]any{
		"description": "Golden terminal bundle generated by Go for cross-runtime verification. The TypeScript test reads this file and verifies the receipt signature using WebCrypto Ed25519, checks the evidence_sha256 binding, and validates the evidence digest.",
		"public_key":  base64.StdEncoding.EncodeToString(pub),
		"evidence":    json.RawMessage(mustMarshalJSON(bundle.Evidence)),
		"receipt":     json.RawMessage(mustMarshalJSON(bundle.Receipt)),
	}

	path := filepath.Join("testdata", "terminal-bundle-golden.json")
	if update := os.Getenv("GOGENERATE_GOLDEN") == "1" || testing.Short() && false; update {
		data, err := json.MarshalIndent(golden, "", "  ")
		if err != nil {
			t.Fatalf("marshal golden: %v", err)
		}
		if err := os.WriteFile(path, data, 0644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("wrote golden file to %s", path)
		return
	}

	// Always write the golden file (this test is also the generator).
	data, err := json.MarshalIndent(golden, "", "  ")
	if err != nil {
		t.Fatalf("marshal golden: %v", err)
	}
	if err := os.WriteFile(path, data, 0644); err != nil {
		t.Fatalf("write golden: %v", err)
	}
	t.Logf("wrote golden file to %s", path)

	// Verify the written file can be read back and parsed.
	readData, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var readBack map[string]json.RawMessage
	if err := json.Unmarshal(readData, &readBack); err != nil {
		t.Fatalf("unmarshal golden: %v", err)
	}
	var readReceipt terminalRunReceipt
	if err := json.Unmarshal(readBack["receipt"], &readReceipt); err != nil {
		t.Fatalf("unmarshal receipt: %v", err)
	}
	if readReceipt.Signature != bundle.Receipt.Signature {
		t.Fatal("golden receipt signature mismatch after round-trip")
	}
	if readReceipt.EvidenceSHA256 != bundle.Evidence.Digest {
		t.Fatal("golden evidence binding mismatch after round-trip")
	}
}

func mustMarshalJSON(v any) []byte {
	data, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return data
}

// TestTerminalBundleEvidenceBinding verifies that BuildTerminalBundle
// produces a receipt whose evidence_sha256 exactly matches the evidence
// digest, and that the signature is valid under the signing key.
func TestTerminalBundleEvidenceBinding(t *testing.T) {
	seed := make([]byte, ed25519.SeedSize)
	key := ed25519.NewKeyFromSeed(seed)

	startedAt := time.Date(2026, 1, 15, 12, 0, 0, 0, time.UTC)
	outcome := FinalRunOutcome{
		Provider:    "test",
		LeaseID:     "cbx_binding",
		RunID:       "run_binding",
		Command:     []string{"echo", "hello"},
		CommandText: "echo hello",
		ExitCode:    0,
		RunStatus:   RunStatusSucceeded,
		StartedAt:   startedAt,
		EndedAt:     startedAt.Add(time.Second),
		Timing: TimingReport{
			TotalMs:   1000,
			CommandMs: 500,
		},
		TerminalLog: runLogSnapshot{Log: "hello\n"},
	}

	bundle, err := BuildTerminalBundle(outcome, key)
	if err != nil {
		t.Fatalf("BuildTerminalBundle: %v", err)
	}

	// Evidence digest must match receipt binding.
	if bundle.Receipt.EvidenceSHA256 != bundle.Evidence.Digest {
		t.Fatalf("evidence_sha256 mismatch: receipt=%s evidence=%s",
			bundle.Receipt.EvidenceSHA256, bundle.Evidence.Digest)
	}

	// Signature must verify.
	if err := verifyTerminalRunReceiptSignature(bundle.Receipt); err != nil {
		t.Fatalf("signature verification: %v", err)
	}

	// Tampering with the evidence digest must break the binding.
	tampered := bundle.Evidence
	tampered.Digest = "0" + tampered.Digest[1:]
	if tampered.Digest == bundle.Receipt.EvidenceSHA256 {
		t.Fatal("tampered digest still matches receipt binding")
	}
}
