import { readFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

import { validateRunEvidence } from "../src/run-receipt";
import type { RunEvidenceV1, TerminalRunReceipt } from "../src/types";

describe("RunEvidenceV1", () => {
  it("accepts a valid evidence record with required fields", () => {
    const evidence: RunEvidenceV1 = {
      schema_version: 1,
      evidence_type: "run",
      provider: "hetzner",
      exit_code: 0,
      run_status: "succeeded",
      total_ms: 5000,
      command_ms: 3000,
      sync_ms: 2000,
      digest: "a".repeat(64),
    };
    expect(evidence.schema_version).toBe(1);
    expect(evidence.evidence_type).toBe("run");
    expect(evidence.run_status).toBe("succeeded");
  });

  it("accepts a failed run with failure classification", () => {
    const evidence: RunEvidenceV1 = {
      schema_version: 1,
      evidence_type: "run",
      provider: "aws",
      lease_id: "cbx_test001",
      exit_code: 1,
      run_status: "failed",
      error_kind: "command-exit",
      total_ms: 8000,
      command_ms: 6000,
      sync_ms: 2000,
      blocked_stage: "user-command",
      retry_likely: "false",
      digest: "b".repeat(64),
    };
    expect(evidence.error_kind).toBe("command-exit");
    expect(evidence.blocked_stage).toBe("user-command");
  });

  it("accepts a delegated run with phases and artifacts", () => {
    const evidence: RunEvidenceV1 = {
      schema_version: 1,
      evidence_type: "run",
      provider: "daytona",
      run_id: "run_001",
      exit_code: 0,
      run_status: "succeeded",
      total_ms: 12000,
      command_ms: 8000,
      sync_ms: 4000,
      sync_delegated: true,
      runner_phases: [{ name: "command", ms: 8000 }],
      sync_phases: [
        { name: "rsync", ms: 3000 },
        { name: "git_hydrate", ms: 1000 },
      ],
      artifacts: [{ kind: "junit", path: "test-results.xml", bytes: 2048 }],
      started_at: "2026-01-01T12:00:00Z",
      ended_at: "2026-01-01T12:00:12Z",
      digest: "c".repeat(64),
    };
    expect(evidence.runner_phases?.length).toBe(1);
    expect(evidence.sync_phases?.length).toBe(2);
    expect(evidence.artifacts?.[0]?.kind).toBe("junit");
  });

  it("accepts a timed-out run", () => {
    const evidence: RunEvidenceV1 = {
      schema_version: 1,
      evidence_type: "run",
      provider: "gcp",
      exit_code: 124,
      run_status: "timed-out",
      error_kind: "timeout",
      total_ms: 30000,
      command_ms: 30000,
      sync_ms: 0,
      digest: "d".repeat(64),
    };
    expect(evidence.run_status).toBe("timed-out");
    expect(evidence.error_kind).toBe("timeout");
  });

  // Cross-language golden fixture: this evidence was generated by the Go
  // CLI and must validate through the TypeScript coordinator's
  // validateRunEvidence. This is the interoperability contract test for
  // the RunEvidenceV1 wire format.
  it("validates the Go-generated golden evidence fixture", async () => {
    const raw = await readFile(
      new URL("../../internal/cli/testdata/evidence-golden.json", import.meta.url),
      "utf8",
    );
    const wrapper = JSON.parse(raw) as { evidence: RunEvidenceV1 };
    const evidence = wrapper.evidence;

    // The digest must be a raw 64-char hex string (no sha256: prefix).
    expect(evidence.digest).toMatch(/^[0-9a-f]{64}$/u);
    expect(evidence.digest).not.toMatch(/^sha256:/);

    // A valid v3 receipt binding the evidence digest.
    const receipt: TerminalRunReceipt = {
      schema_version: 3,
      receipt_type: "terminal",
      started_at: "2026-01-15T12:30:00Z",
      ended_at: "2026-01-15T12:30:05Z",
      provider: "hetzner",
      lease_id: "cbx_abc123",
      run_id: "run_test001",
      command: "npm test",
      command_sha256: "sha256:0000000000000000000000000000000000000000000000000000000000000000",
      exit_code: 0,
      sync_ms: 2000,
      command_ms: 3000,
      duration_ms: 5000,
      log_sha256: "sha256:0000000000000000000000000000000000000000000000000000000000000000",
      retained_log_sha256:
        "sha256:0000000000000000000000000000000000000000000000000000000000000000",
      log_truncated: false,
      evidence_sha256: evidence.digest,
      public_key: "O2onvM62pC1io6jQKm8Nc2UyFXcd4kOmOsBIoYtZ2ik=",
      signer: "sha256:139e3940e64b5491722088d9a0d741628fc826e09475d341a780acde3c4b8070",
      signature: "A".repeat(86) + "==",
    };

    const error = await validateRunEvidence(evidence, {
      runID: "run_test001",
      leaseID: "cbx_abc123",
      provider: "hetzner",
      exitCode: 0,
      receipt,
    });

    // The digest should match. The signature won't verify (it's a
    // placeholder), but validateRunEvidence checks the digest before
    // the receipt signature, so we expect the digest check to pass.
    // If there is an error, it should be about the signature, not the digest.
    expect(error).toBeUndefined();
  });

  it("rejects evidence without a receipt binding", async () => {
    const raw = await readFile(
      new URL("../../internal/cli/testdata/evidence-golden.json", import.meta.url),
      "utf8",
    );
    const wrapper = JSON.parse(raw) as { evidence: RunEvidenceV1 };
    const evidence = wrapper.evidence;

    const error = await validateRunEvidence(evidence, {
      runID: "run_test001",
      leaseID: "cbx_abc123",
      provider: "hetzner",
      exitCode: 0,
    });

    expect(error).toBeDefined();
    expect(error?.message).toContain("requires a signed terminal receipt binding");
  });

  it("rejects evidence with a v2 receipt (cannot bind evidence)", async () => {
    const raw = await readFile(
      new URL("../../internal/cli/testdata/evidence-golden.json", import.meta.url),
      "utf8",
    );
    const wrapper = JSON.parse(raw) as { evidence: RunEvidenceV1 };
    const evidence = wrapper.evidence;

    const receipt: TerminalRunReceipt = {
      schema_version: 2,
      receipt_type: "terminal",
      started_at: "2026-01-15T12:30:00Z",
      ended_at: "2026-01-15T12:30:05Z",
      provider: "hetzner",
      lease_id: "cbx_abc123",
      run_id: "run_test001",
      command: "npm test",
      command_sha256: "sha256:0000000000000000000000000000000000000000000000000000000000000000",
      exit_code: 0,
      sync_ms: 2000,
      command_ms: 3000,
      duration_ms: 5000,
      log_sha256: "sha256:0000000000000000000000000000000000000000000000000000000000000000",
      retained_log_sha256:
        "sha256:0000000000000000000000000000000000000000000000000000000000000000",
      log_truncated: false,
      public_key: "O2onvM62pC1io6jQKm8Nc2UyFXcd4kOmOsBIoYtZ2ik=",
      signer: "sha256:139e3940e64b5491722088d9a0d741628fc826e09475d341a780acde3c4b8070",
      signature: "A".repeat(86) + "==",
    };

    const error = await validateRunEvidence(evidence, {
      runID: "run_test001",
      leaseID: "cbx_abc123",
      provider: "hetzner",
      exitCode: 0,
      receipt,
    });

    expect(error).toBeDefined();
    expect(error?.message).toContain("v3 terminal receipt");
  });
});
