import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { validateRunEvidence } from "../src/run-receipt.ts";
import type { RunEvidenceV1, TerminalRunReceipt } from "../src/types.ts";

// Cross-runtime terminal bundle interop test.
//
// This test reads a golden terminal bundle (evidence + signed V3 receipt)
// generated by the Go CLI's BuildTerminalBundle function and verifies:
//
// 1. The evidence passes the TypeScript structural validator.
// 2. The evidence digest matches the receipt's evidence_sha256 binding.
// 3. The Ed25519 signature on the receipt verifies under the public key
//    using the TypeScript WebCrypto implementation.
//
// This proves that Go-signed receipts are verifiable by the TypeScript
// worker, closing the cross-runtime signature verification gap.

const goldenPath = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../internal/cli/testdata/terminal-bundle-golden.json",
);

interface GoldenBundle {
  description: string;
  public_key: string;
  evidence: RunEvidenceV1;
  receipt: TerminalRunReceipt;
}

const golden = JSON.parse(readFileSync(goldenPath, "utf-8")) as GoldenBundle;

// Terminal receipt signing fields (must match run-receipt.ts).
const terminalReceiptSigningFields = [
  "schema_version",
  "receipt_type",
  "started_at",
  "ended_at",
  "provider",
  "lease_id",
  "slug",
  "run_id",
  "command",
  "command_sha256",
  "exit_code",
  "sync_ms",
  "command_ms",
  "duration_ms",
  "log_sha256",
  "retained_log_sha256",
  "log_truncated",
  "evidence_sha256",
  "public_key",
  "signer",
];

function terminalReceiptSigningBytes(receipt: TerminalRunReceipt): Uint8Array {
  const encoder = new TextEncoder();
  const prefix = "crabbox-terminal-receipt-v3\0";
  const parts = [encoder.encode(prefix)];
  for (const field of terminalReceiptSigningFields) {
    const value = encoder.encode(
      String((receipt as unknown as Record<string, unknown>)[field] ?? ""),
    );
    const length = new Uint8Array(4);
    new DataView(length.buffer).setUint32(0, value.byteLength);
    parts.push(length, value);
  }
  const payload = new Uint8Array(parts.reduce((total, part) => total + part.byteLength, 0));
  let offset = 0;
  for (const part of parts) {
    payload.set(part, offset);
    offset += part.byteLength;
  }
  return payload;
}

function decodeBase64(value: string): Uint8Array {
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

describe("Go-generated terminal bundle interop", () => {
  it("has a valid golden bundle", () => {
    expect(golden.public_key).toBeTruthy();
    expect(golden.evidence).toBeTruthy();
    expect(golden.receipt).toBeTruthy();
    expect(golden.receipt.schema_version).toBe(3);
    expect(golden.receipt.receipt_type).toBe("terminal");
  });

  it("passes TypeScript evidence structural validation", async () => {
    // The binding uses the receipt to provide the evidence_sha256 binding.
    const err = await validateRunEvidence(golden.evidence, {
      runID: golden.evidence.run_id ?? "",
      leaseID: golden.evidence.lease_id ?? "",
      provider: golden.evidence.provider,
      exitCode: golden.evidence.exit_code,
      receipt: golden.receipt,
    });
    expect(
      err,
      `expected evidence to be accepted: ${err instanceof Error ? err.message : String(err)}`,
    ).toBeUndefined();
  });

  it("evidence digest matches receipt evidence_sha256 binding", () => {
    expect(golden.evidence.digest).toBe(golden.receipt.evidence_sha256);
    expect(golden.evidence.digest).toMatch(/^[0-9a-f]{64}$/);
  });

  it("Ed25519 signature verifies under WebCrypto", async () => {
    const publicKeyBytes = decodeBase64(golden.public_key);
    expect(publicKeyBytes.byteLength).toBe(32);

    const key = await crypto.subtle.importKey("raw", publicKeyBytes, "Ed25519", false, ["verify"]);
    const signature = decodeBase64(golden.receipt.signature);
    expect(signature.byteLength).toBe(64);

    const signingBytes = terminalReceiptSigningBytes(golden.receipt);
    const valid = await crypto.subtle.verify("Ed25519", key, signature, signingBytes);
    expect(valid, "Go-generated Ed25519 signature must verify under TypeScript WebCrypto").toBe(
      true,
    );
  });

  it("rejects a tampered signature", async () => {
    const publicKeyBytes = decodeBase64(golden.public_key);
    const key = await crypto.subtle.importKey("raw", publicKeyBytes, "Ed25519", false, ["verify"]);
    const signature = decodeBase64(golden.receipt.signature);
    // Flip one bit in the signature.
    signature[0] ^= 0x01;
    const signingBytes = terminalReceiptSigningBytes(golden.receipt);
    const valid = await crypto.subtle.verify("Ed25519", key, signature, signingBytes);
    expect(valid).toBe(false);
  });

  it("rejects a tampered receipt field", async () => {
    const publicKeyBytes = decodeBase64(golden.public_key);
    const key = await crypto.subtle.importKey("raw", publicKeyBytes, "Ed25519", false, ["verify"]);
    const signature = decodeBase64(golden.receipt.signature);

    // Tamper with the exit_code — this changes the signing payload but
    // not the signature, so verification must fail.
    const tampered = { ...golden.receipt, exit_code: golden.receipt.exit_code === 0 ? 1 : 0 };
    const signingBytes = terminalReceiptSigningBytes(tampered);
    const valid = await crypto.subtle.verify("Ed25519", key, signature, signingBytes);
    expect(valid).toBe(false);
  });
});
