import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { validateRunEvidence, verifyTerminalReceipt } from "../src/run-receipt.ts";
import type { RunEvidenceV1, RunRecord, TerminalRunReceipt } from "../src/types.ts";

// Cross-runtime terminal bundle interop test.
//
// This test reads a golden terminal bundle (evidence + signed V3 receipt)
// generated by the Go CLI's BuildTerminalBundle function and verifies it
// using the PRODUCTION TypeScript verification functions:
//
// 1. validateRunEvidence() — the same function the coordinator uses to
//    validate evidence before persistence.
// 2. verifyTerminalReceipt() — the same function the coordinator uses to
//    verify terminal receipts before accepting a finish request.
//
// This proves that Go-signed bundles are verifiable by the production
// TypeScript coordinator, closing the cross-runtime verification gap.

const goldenPath = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../internal/cli/testdata/terminal-bundle-golden.json",
);

interface GoldenBundle {
  description: string;
  public_key: string;
  evidence: RunEvidenceV1;
  receipt: TerminalRunReceipt;
}

const golden = JSON.parse(readFileSync(goldenPath, "utf-8")) as GoldenBundle;

// Build a RunRecord that matches the golden bundle's binding fields.
// The production verifyTerminalReceipt() checks that the receipt's
// provider, lease_id, slug, run_id, command, exit_code, sync_ms,
// command_ms, log_truncated, started_at, and log digests all match
// the run record and finish inputs.
function goldenRunRecord(): RunRecord {
  return {
    id: golden.receipt.run_id,
    leaseID: golden.receipt.lease_id ?? "",
    slug: golden.receipt.slug,
    owner: "alice@example.com",
    org: "example-org",
    provider: golden.receipt.provider,
    class: "standard",
    serverType: "test",
    command: ["npm", "test"],
    state: "succeeded",
    exitCode: golden.receipt.exit_code,
    syncMs: golden.receipt.sync_ms,
    commandMs: golden.receipt.command_ms,
    logBytes: golden.evidence.command_text?.length ?? 0,
    logTruncated: golden.receipt.log_truncated,
    startedAt: golden.receipt.started_at,
  };
}

describe("Go-generated terminal bundle interop (production verifier)", () => {
  it("has a valid golden bundle", () => {
    expect(golden.public_key).toBeTruthy();
    expect(golden.evidence).toBeTruthy();
    expect(golden.receipt).toBeTruthy();
    expect(golden.receipt.schema_version).toBe(3);
    expect(golden.receipt.receipt_type).toBe("terminal");
  });

  it("passes TypeScript evidence structural validation", async () => {
    const err = await validateRunEvidence(golden.evidence, {
      runID: golden.evidence.run_id ?? "",
      leaseID: golden.evidence.lease_id ?? "",
      provider: golden.evidence.provider,
      exitCode: golden.evidence.exit_code,
      receipt: golden.receipt,
    });
    expect(
      err,
      `expected evidence to be accepted: ${err instanceof Error ? err.message : String(err)}`,
    ).toBeUndefined();
  });

  it("evidence digest matches receipt evidence_sha256 binding", () => {
    expect(golden.evidence.digest).toBe(golden.receipt.evidence_sha256);
    expect(golden.evidence.digest).toMatch(/^[0-9a-f]{64}$/);
  });

  it("passes the production verifyTerminalReceipt() function", async () => {
    // This is the real production verification path. If this passes,
    // the Go-generated bundle would be accepted by the coordinator.
    const log = "all tests passed\n";
    const receipt = await verifyTerminalReceipt(golden.receipt, {
      run: goldenRunRecord(),
      exitCode: golden.receipt.exit_code,
      syncMs: golden.receipt.sync_ms,
      commandMs: golden.receipt.command_ms,
      log,
      logTruncated: golden.receipt.log_truncated,
      observedAt: new Date(golden.receipt.ended_at),
    });
    expect(receipt.run_id).toBe(golden.receipt.run_id);
    expect(receipt.signature).toBe(golden.receipt.signature);
    expect(receipt.evidence_sha256).toBe(golden.evidence.digest);
  });

  it("rejects a tampered receipt with wrong exit_code", async () => {
    const tampered = { ...golden.receipt, exit_code: 1 };
    await expect(
      verifyTerminalReceipt(tampered, {
        run: goldenRunRecord(),
        exitCode: golden.receipt.exit_code,
        syncMs: golden.receipt.sync_ms,
        commandMs: golden.receipt.command_ms,
        log: "all tests passed\n",
        logTruncated: golden.receipt.log_truncated,
        observedAt: new Date(golden.receipt.ended_at),
      }),
    ).rejects.toThrow();
  });

  it("rejects a receipt with mismatched log content", async () => {
    await expect(
      verifyTerminalReceipt(golden.receipt, {
        run: goldenRunRecord(),
        exitCode: golden.receipt.exit_code,
        syncMs: golden.receipt.sync_ms,
        commandMs: golden.receipt.command_ms,
        log: "wrong log content\n",
        logTruncated: golden.receipt.log_truncated,
        observedAt: new Date(golden.receipt.ended_at),
      }),
    ).rejects.toThrow(/log binding/);
  });
});
